import React from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import { ContactsHeroIllustration } from '@/illustrations';

function index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Hero
          title='Контакты'
          descr="Контакты"
          illustration='../lotties/contacts.json'
          classes='contacts'
        />
        <Footer/>
      </main>
    </>
  )
}

export default index