import React from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import { BlogHeroIllustration } from '@/illustrations';

function index() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Hero
          title='Blog'
          descr='blog lorem ipsum dolor sit amet lore mauris'
          illustration='../lotties/blog.json'
          classes='blog'
        />
        <Footer/>
      </main>
    </>
  )
}

export default index